#!/usr/bin/env python3
"""
Binary to CVBasic Data Converter

Copyright (c) 2025 Troy Schrapel
License: MIT
GitHub: https://github.com/visrealm/retroplex

==============================================================================
USAGE
==============================================================================

python bin2cvb.py [options] <binfile> [binfile2 ...]

ARGUMENTS:
  binfile             Binary file(s) or pattern to convert. Supports wildcards.

OPTIONS:
  -o, --outfile FILE  Output file path. Defaults to <binfile>.bas
  -c, --chunksize N   Add #CHUNKSIZE N pragma to output file header.
                      This will cause cvpletter.py to split data into N-byte
                      chunks when compressing.
  --banking           Add #BANKING pragma to enable banking mode in cvpletter.py
  --bank0 LABELS      Add #BANK0 pragma with comma-separated label list
  --bank N            Add #BANK N pragma to specify starting bank number

EXAMPLES:
  python bin2cvb.py data.bin
  python bin2cvb.py -o output.bas data.bin
  python bin2cvb.py -c 8192 largedata.bin
  python bin2cvb.py --banking --bank0 menu,title --bank 2 data.bin
  python bin2cvb.py -c 4096 *.bin

==============================================================================
"""

import sys
import argparse
import glob
import os
import re
from datetime import datetime


def _to_camel(name: str) -> str:
    """Convert a base filename to lowerCamelCase (vdp-detect -> vdpDetect)."""
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", name) if p]
    if not parts:
        return name
    head, *tail = parts
    return head.lower() + "".join(t.capitalize() for t in tail)


def _to_upper_snake(name: str) -> str:
    """Convert a base filename to UPPER_SNAKE_CASE (vdp-detect -> VDP_DETECT)."""
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", name) if p]
    return "_".join(p.upper() for p in parts if p)


def _write_header(output, source_path: str, output_path: str, byte_count: int, cmd: str,
                  chunksize=None, banking=False, bank0_labels=None, start_bank=None) -> None:
    """Write a brief provenance header similar to cvpletter output."""
    output_basename = os.path.basename(output_path)
    generated_at = datetime.now().isoformat(timespec="seconds")

    # Write pragmas first if any are specified
    if chunksize or banking:
        if chunksize:
            output.write(f"' #CHUNKSIZE {chunksize}\n")
        if banking:
            output.write("' #BANKING\n")
            if bank0_labels:
                output.write(f"' #BANK0 {', '.join(bank0_labels)}\n")
            if start_bank is not None:
                output.write(f"' #BANK {start_bank}\n")
        output.write("'\n")

    output.write("' ====================================================\n")
    output.write("' This file was generated using bin2cvb.py\n")
    output.write("'\n")
    output.write("' Copyright (c) 2026 Troy Schrapel\n")
    output.write("'\n")
    output.write(f"' generated: {generated_at}\n")
    output.write(f"' source: {source_path}\n")
    output.write(f"' cmd:    {cmd}\n")
    output.write(f"' output: {output_basename}\n")
    output.write(f"' size:   {byte_count} bytes\n")
    output.write("'\n")
    output.write("' ====================================================\n")
    output.write("' WARNING! Do NOT edit this file. Edit source file\n")
    output.write("' ====================================================\n\n")

def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        add_help=True)
    parser.add_argument('-o', '--outfile', help='output file - defaults to base input file name with .bas extension')
    parser.add_argument('-c', '--chunksize', type=int, metavar='N',
                        help='add #CHUNKSIZE N pragma to output file header')
    parser.add_argument('--banking', action='store_true',
                        help='add #BANKING pragma to output file header')
    parser.add_argument('--bank0', metavar='LABELS',
                        help='add #BANK0 pragma with comma-separated label list')
    parser.add_argument('--bank', type=int, metavar='N',
                        help='add #BANK N pragma to specify starting bank number')
    parser.add_argument('binfile', nargs='+', help='binary file or pattern to match multiple files')
    args = vars(parser.parse_args())

    bin_files = []
    for pattern in args['binfile']:
        bin_files.extend(glob.glob(pattern))

    if not bin_files:
        print("No matching files found.")
        sys.exit(1)

    for filename in bin_files:
        output_filename = args['outfile'] if args['outfile'] else filename + ".bas"
        base_name = os.path.splitext(os.path.basename(filename))[0]
        label = _to_camel(base_name)

        try:
            with open(filename, mode='rb') as binFile:
                data = binFile.read()
                byte_count = len(data)

            # Build command string for header
            cmd_parts = ["python", "bin2cvb.py"]
            if args['outfile']:
                cmd_parts.extend(["-o", args['outfile']])
            if args['chunksize']:
                cmd_parts.extend(["-c", str(args['chunksize'])])
            if args['banking']:
                cmd_parts.append("--banking")
            if args['bank0']:
                cmd_parts.extend(["--bank0", args['bank0']])
            if args['bank']:
                cmd_parts.extend(["--bank", str(args['bank'])])
            cmd_parts.append(filename)
            cmd_string = " ".join(cmd_parts)

            # Parse bank0 labels if provided
            bank0_labels = None
            if args['bank0']:
                bank0_labels = [l.strip() for l in args['bank0'].split(',')]

            with open(output_filename, mode='w') as output:
                _write_header(output, filename, output_filename, byte_count, cmd_string,
                            chunksize=args['chunksize'],
                            banking=args['banking'],
                            bank0_labels=bank0_labels,
                            start_bank=args['bank'])

                # Write size constant
                constant_name = _to_upper_snake(base_name)
                output.write(f"CONST {constant_name}_SIZE = {byte_count}\n\n")

                output.write(f"{label}:\n")
                for i in range(0, byte_count, 8):
                    chunk = data[i:i + 8]
                    byte_str = ["${:02x}".format(b) for b in chunk]
                    output.write("  DATA BYTE {0}\n".format(", ".join(byte_str)))
                output.write(f"{label}End:\n")

        except FileNotFoundError:
            print(f"The file '{filename}' was not found.")
            continue
        except IOError:
            print(f"An error occurred while reading the file '{filename}'.")
            continue

    return

# program entry
if __name__ == "__main__":
    sys.exit(main())
