#!/usr/bin/env python3
from PIL import Image

import os
import sys
from pathlib import Path
from datetime import datetime

# ------------------------------------------------------------
# Convert an 8-pixel row (4 pixels wide) into a 4-bit nibble
# ------------------------------------------------------------
def row_to_nibble(pixels, y):
    nib = 0
    for x in range(4):
        bit = 0 if pixels[x, y] == 0 else 1  # 1 = black pixel, 0 = white
        nib = (nib << 1) | bit
    return nib


# ------------------------------------------------------------
# Convert a single 4x8 glyph into four bytes
# Each byte = two rows: high nibble = row N, low nibble = row N+1
# ------------------------------------------------------------
def encode_glyph(pixels):
    bytes_out = []
    for row in range(0, 8, 2):
        high = row_to_nibble(pixels, row)
        low  = row_to_nibble(pixels, row + 1)
        byte = (high << 4) | low
        bytes_out.append(byte)
    return bytes_out


def _write_header(output, source_path: str, output_path: str, byte_count: int, cmd: str) -> None:
    """Write a brief provenance header similar to cvpletter output."""
    output_basename = os.path.basename(output_path)
    generated_at = datetime.now().isoformat(timespec="seconds")
    output.write("' ====================================================\n")
    output.write("' This file was generated using bmpfont2cvb.py\n")
    output.write("'\n")
    output.write("' Copyright (c) 2026 Troy Schrapel\n")
    output.write("'\n")
    output.write(f"' generated: {generated_at}\n")
    output.write(f"' source: {source_path}\n")
    output.write(f"' cmd:    {cmd}\n")
    output.write(f"' output: {output_basename}\n")
    output.write(f"' size:   {byte_count} bytes\n")
    output.write("'\n")
    output.write("' ====================================================\n")
    output.write("' WARNING! Do NOT edit this file. Edit source file\n")
    output.write("' ====================================================\n\n")


# ------------------------------------------------------------
# Main
# ------------------------------------------------------------
def main():
    if len(sys.argv) != 3:
        print("Usage: bmpfont2cvb.py input.png output.bas")
        sys.exit(1)

    infile = sys.argv[1]
    outfile = sys.argv[2]

    img = Image.open(infile).convert("1")  # force 1bpp
    width, height = img.size

    CHAR_W = 4
    CHAR_H = 8
    CHARS_ACROSS = 16
    CHARS_DOWN = 4

    expected_w = CHAR_W * CHARS_ACROSS
    expected_h = CHAR_H * CHARS_DOWN

    if width != expected_w or height != expected_h:
        print(f"Error: image must be {expected_w}x{expected_h} pixels")
        sys.exit(1)

    out = []

    ascii_start = 32
    ascii_end = 95
    ascii_code = ascii_start

    for cy in range(CHARS_DOWN):
        for cx in range(CHARS_ACROSS):
            if ascii_code > ascii_end:
                break

            # Extract glyph region
            x0 = cx * CHAR_W
            y0 = cy * CHAR_H
            glyph = img.crop((x0, y0, x0 + CHAR_W, y0 + CHAR_H))

            # Encode glyph
            encoded = encode_glyph(glyph.load())

            # Format output line
            hexbytes = ", ".join(f"${b:02X}" for b in encoded)
            comment = f" ' ASCII {ascii_code} '{chr(ascii_code)}'"
            out.append(f"DATA BYTE {hexbytes}{comment}")

            ascii_code += 1


    cmd_parts = ["python", "bmpfont2cvb.py"]
    cmd_parts.extend([infile, outfile])
    cmd_string = " ".join(cmd_parts)

    # Write output file
    with open(outfile, "w") as f:
        _write_header(f, infile, outfile, 256, cmd_string)
        for line in out:
            f.write(line + "\n")

    print(f"Wrote {len(out)} character definitions to {outfile}")


if __name__ == "__main__":
    main()